---
new_page_extension: md
auto_deploy: false
admin_path: "/forestry"
webhook_url: 
sections:
- type: heading
  label: Carta di Menu
- type: document
  path: _data/1-noiconsigliamo.yml
  label: Noi consigliamo
- type: document
  path: _data/2-antipasti.yml
  label: Antipasti
- type: document
  path: _data/3-pasta.yml
  label: Pasta
- type: document
  path: _data/4-pesce.yml
  label: Pesce
- type: document
  path: _data/5-carne.yml
  label: Carne
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle update; bundle install
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
